config/routes.rb
MyAgregat::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations", :passwords => "users/passwords", }

  root 'welcome#index'

  resources :categories, :only => [:show] do
    scope module: :categories do
      resources :machines, :only => [:index]
    end
  end

  resources :users, :only => [:show] do
    scope module: :users do
      resources :machines, :except=>:destroy do
        member do
          get :activate
          get :archivate
        end

        collection do
          get :archive
        end
      end
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  has_many :machines
end

app/models/machine.rb
class Machine < ActiveRecord::Base
  include Authority::Abilities
  belongs_to :category
  belongs_to :user

  validates :user, :category, :name, :location, :charge, :presence => true

  scope :active, -> {where(:active=>true)}
  scope :archive, -> {where(:active=>false)}

  before_validation :set_specification

  def set_specification
    self.specification = {} if self.specification.blank?
  end

  def activate
    self.update_attribute(:active, true)
  end

  def archivate
    self.update_attribute(:active, false)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable
  include Authority::UserAbilities

  phony_normalize :phone, :country_code=>'RU'
  validates_plausible_phone :phone, :country_code=>'7'
  validates :phone, :uniqueness => true
  validates :phone, :name, :presence => true

  before_validation :generate_password, :on => :create
  after_create :send_password
  has_many :machines

  def generate_password forced = false
    require 'securerandom'
    self.password = SecureRandom.hex[0..5] if password.blank? or forced
  end

  def send_password
    puts 'I DO SEND PASSWORD'
    puts password
    update_column(:sms_sended_at, Time.now)
  end

  def send_reset_password_instructions
    generate_password(true)
    send_password
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :phone) }
    devise_parameter_sanitizer.for(:password_new) { |u| u.permit(:phone) }
  end
end

app/controllers/categories/machines_controller.rb
class Categories::MachinesController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @machines = @category.machines.active.page params[:page]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    category = Category.find(params[:id])
    redirect_to category_machines_path(category)
  end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @machines = @category.machines.active.page params[:page]
  end
end

app/controllers/users/machines_controller.rb
class Users::MachinesController < ApplicationController
  before_action :set_user

  def index
    authorize_action_for(Machine, @user)
    @machines = @user.machines.active.page params[:page]
  end

  def archive
    authorize_action_for(Machine, @user)
    @machines = @user.machines.archive.page params[:page]
    render :index
  end

  def new
    @machine = @user.machines.new
    authorize_action_for(@machine)
  end

  def create
    @machine = @user.machines.new(machine_params)
    authorize_action_for(@machine)
    if @machine.save
      redirect_to user_machine_path(@user, @machine)
    else
      render :new
    end
  end

  def edit
    @machine = @user.machines.find(params[:id])
    authorize_action_for(@machine)
  end

  def update
    @machine = @user.machines.find(params[:id])
    authorize_action_for(@machine)
    if @machine.update(machine_params)
      redirect_to user_machine_path(@user, @machine)
    else
      render :edit
    end
  end

  def show
    @machine = @user.machines.find(params[:id])
  end

  def activate
    machine = @user.machines.find(params[:id])
    machine.activate
    redirect_to :back
  end

  def archivate
    machine = @user.machines.find(params[:id])
    machine.archivate
    redirect_to :back
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def machine_params
    params.require(:machine).permit(:category_id, :name, :location, :charge, :driver_charge, :description)
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  def resource_params
    res_par = super
    begin
      res_par[:phone] = Phony.normalize(res_par[:phone]) if res_par[:phone]
    rescue
    end
    res_par
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  # POST /resource
  def create
    build_resource(sign_up_params)

    if resource.save
      set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
      expire_session_data_after_sign_in!
      respond_with resource, :location => after_inactive_sign_up_path_for(resource)
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  def after_inactive_sign_up_path_for resource
    new_user_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    redirect_to user_machines_path(user)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end
end

app/views/categories/machines/index.html.haml
- @machines.each do |machine|
  = render_cell :machine, :display_common, machine

= paginate @machines

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to Settings.app.title, root_url, :class => 'navbar-brand'
    .collapse.navbar-collapse
      = render_navigation :expand_all => true, :renderer => :bootstrap

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : Settings.app.title
    %meta{:content => content_for?(:description) ? yield(:description) : Settings.app.title, :name => "description"}
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
    = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .col-md-3
              = render_cell :categories, :display
            .col-md-9
              = render 'layouts/messages'
              = yield
          %footer

app/views/machines/index.html.haml
- @machines.each do |machine|
  = render_cell :machine, :display, machine

= paginate @machines

app/views/users/machines/_form.html.haml
= simple_form_for [@user, @machine] do |f|
  = f.error_notification
  = f.association :category
  = f.input :name
  = f.input :location
  = f.input :charge
  = f.input :driver_charge
  = f.input :description
  = f.submit

app/views/users/machines/edit.html.haml
= render 'form'

app/views/users/machines/index.html.haml
- if @user == current_user
  .row
    = active_link_to t('.active'), user_machines_path(@user)
    = active_link_to t('.archive'), archive_user_machines_path(@user)

- @machines.each do |machine|
  = render_cell :machine, :display_own, machine

= paginate @machines

app/views/users/machines/new.html.haml
= render 'form'

app/views/users/machines/show.html.haml
.row
  = @machine.name
  = @machine.location
  = @machine.charge
  = @machine.driver_charge
  = @machine.user.name
  - @machine.specification.each do |key, value|
    = key
    = value
  = @machine.description
  = link_to t('.edit'), edit_user_machine_path(@machine.user, @machine) if @machine.updatable_by?(current_user)
  = link_to t('.activate'), activate_user_machine_path(@machine.user, @machine) if !@machine.active? and @machine.updatable_by?(current_user)
  = link_to t('.archivate'), archivate_user_machine_path(@machine.user, @machine) if @machine.active? and @machine.updatable_by?(current_user)

app/views/welcome/index.html.haml
%h1 Welcome#index
%p Find me in app/views/welcome/index.html.haml